
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - alphacollege

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress
        
      - name: Use Node.js 
      - uses: actions/setup-node@v3
        with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
        run: npm install
      
      - name: Tar files
        run: tar -cvf php-app.tar.gz .
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: php-app.tar.gz
          path: ./php-app.tar.gz
      - name: Notify build events
        uses: notify-events/github-action@main
        with:
          token: $(( secrets.NE_CHANNEL_TOKEN }}
          success: Build {{ github.ref }} successfully
          
  sonar_job:
    name: sonar_scanning
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
  deploy:
    runs-on: ubuntu-latest
    needs: sonar_job
    environment:
      name: 'uat'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: php-app.tar.gz

      - name: Extract Tar archive
        run: tar -xvf php-app.tar.gz . && rm -rf php-app.tar.gz


      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'alphacollege'
          slot-name: 'uat'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_50A23098CC514F16B22BADBB43B6EF40 }}
          package: .
